/// Master catalog of default English strings (Source of Truth).
/// Used as the fallback dictionary and for exporting translation templates.
const Map<String, String> defaultEnglishStrings = {
  // Common UI actions & generic terms
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.copy': 'Copy',
  'common.paste': 'Paste',
  'common.connect': 'Connect',
  'common.disconnect': 'Disconnect',
  'common.reconnect': 'Reconnect',
  'common.status': 'Status',
  'common.search': 'Search...',
  'common.refresh': 'Refresh',
  'common.apply': 'Apply',
  'common.close': 'Close',
  'common.error': 'Error',
  'common.success': 'Success',
  'common.unknown': 'Unknown',
  'common.enabled': 'Enabled',
  'common.disabled': 'Disabled',

  // Sidebar Navigation
  'sidebar.nav_hosts': 'Hosts',
  'sidebar.nav_keychain': 'Keychain',
  'sidebar.nav_tunnels': 'Port Forwarding',
  'sidebar.nav_snippets': 'Snippets',
  'sidebar.nav_logs': 'Logs',
  'sidebar.nav_plugins': 'Plugins',
  'sidebar.nav_settings': 'Settings',
  'sidebar.collapse': 'Collapse sidebar',
  'sidebar.expand': 'Expand sidebar',

  // Settings & Security
  'settings.title': 'Settings & Security',
  'settings.security_vault_title': 'Security & Vault',
  'settings.vault.auto_lock_title': 'Auto-Lock Timeout',
  'settings.vault.auto_lock_subtitle':
      'Lock database after {minutes} minutes of inactivity',
  'settings.vault.auto_lock_minutes': '{minutes} minutes',
  'settings.vault.auto_lock_5m': '5 minutes',
  'settings.vault.auto_lock_15m': '15 minutes',
  'settings.vault.auto_lock_30m': '30 minutes',
  'settings.vault.auto_lock_1h': '1 hour',
  'settings.vault.auto_lock_never': 'Never',
  'settings.vault.change_password_title': 'Change Master Password',
  'settings.vault.change_password_subtitle':
      'Re-encrypt SQLCipher database with a new Argon2id key',
  'settings.vault.set_password_title': 'Set Master Password',
  'settings.vault.set_password_subtitle':
      'Protect database and SSH keys with Argon2id encryption',
  'settings.vault.disable_password_title': 'Disable Master Password',
  'settings.vault.disable_password_subtitle':
      'The vault will remain open without prompting for a password when launching the app',
  'settings.vault.lock_now_title': 'Lock Vault Now',
  'settings.vault.lock_now_subtitle':
      'Securely wipe encryption keys from active memory',

  // Terminal & Appearance
  'settings.terminal_appearance_title': 'Terminal Appearance',
  'settings.terminal.color_scheme_label': 'Color Scheme',
  'settings.terminal.current_scheme': 'Current scheme: {scheme}',
  'settings.terminal.font_size_label': 'Font Size',
  'settings.terminal.font_family_label': 'Font Family',

  // Backup & Storage
  'settings.backup_storage_title': 'Backup & Storage',
  'settings.backup.export_title': 'Export Encrypted Vault Backup',
  'settings.backup.export_subtitle':
      'Save encrypted archive (.shellit-vault) protected by master key',
  'settings.backup.import_title': 'Import Vault Backup',
  'settings.backup.import_subtitle':
      'Restore hosts, keys and snippets from encrypted file',

  // Language & Translation
  'settings.language_title': 'Language & Translation',
  'settings.language.select_label': 'Active Language',
  'settings.language.current': 'Current: {lang}',
  'settings.language.builtin_english': 'English (Built-in)',
  'settings.language.export_template_btn':
      'Export Translation Template (.json)',
  'settings.language.export_subtitle':
      'Export complete master string dictionary to create custom language plugins',
  'settings.language.export_template_dialog_title':
      'Export Localization Template',
  'settings.language.export_template_dialog_desc':
      'Save shellit_strings_template.json to create or customize language packs for Shellit:',
  'settings.language.export_template_success':
      'Template exported successfully to {path}',
  'settings.language.export_template_error':
      'Failed to export template: {error}',

  // Synchronization
  'settings.sync_title': 'Synchronization & Multi-Device',

  // Session Logging & Diagnostics
  'settings.logs_title': 'Logs & Diagnostics',
  'settings.logging_title': 'Session Audit & Logging',
  'settings.logging.write_disk_title': 'Write System Logs to Disk',
  'settings.logging.write_disk_subtitle':
      'Persists rotated diagnostic logs (up to 2x 5MB) for crash analysis',
  'settings.logging.min_disk_log_title': 'Minimum Disk Log Level',
  'settings.logging.min_disk_log_subtitle':
      'Filter minimum severity before writing to log files',
  'settings.logging.recording_policy_title':
      'Terminal Session Recording Policy',
  'settings.logging.recording_policy_subtitle':
      'Capture terminal sessions (asciinema .cast and plain text .log)',
  'settings.logging.recording_mode_label': 'Session Recording Mode',
  'settings.logging.open_logs_dir_title': 'Open Logs Directory',
  'settings.logging.open_audit_logs_btn': 'Open Audit Log Viewer',
  'settings.logging.clear_logs_title': 'Clear Disk Logs',
  'settings.logging.clear_logs_subtitle':
      'Erase all historical log files from storage',

  // Hosts & Catalog
  'hosts.title': 'Hosts',
  'hosts.search_placeholder': 'Search hosts by name, IP, or tag...',
  'hosts.btn_new_host': 'Add Host',
  'hosts.quick_connect_placeholder': 'ssh user@hostname',
  'hosts.empty_title': 'No hosts found',
  'hosts.empty_desc': 'Create a new host or adjust search filters.',
  'hosts.status.latency_ms': '{ms} ms',
  'hosts.status.offline': 'Offline',
  'hosts.status.connecting': 'Connecting to {host}...',
  'hosts.status.connected': 'Connected',
  'hosts.card.env_prod': 'PROD',
  'hosts.card.env_stage': 'STAGE',
  'hosts.card.env_dev': 'DEV',
  'hosts.view_grid': 'Grid View',
  'hosts.view_dense': 'Dense List View',
  'hosts.view_tree': 'Folder Tree View',

  // Host Card & Context Menu & Form
  'hosts.card.tooltip_sftp': 'Open SFTP',
  'hosts.card.tooltip_edit': 'Edit Host',
  'hosts.card.tooltip_connect': 'Connect Terminal',
  'hosts.card.tooltip_more': 'More Actions',
  'hosts.context_menu.quick_connect': 'Quick Connect',
  'hosts.context_menu.connect': 'Connect',
  'hosts.context_menu.ssh_terminal': 'SSH Terminal',
  'hosts.context_menu.sftp_explorer': 'SFTP Explorer',
  'hosts.context_menu.open_split': 'Open in New Split',
  'hosts.context_menu.edit_details': 'Edit Host Details',
  'hosts.context_menu.move_to_folder': 'Move to Folder',
  'hosts.context_menu.root_folder': 'None (Root)',
  'hosts.context_menu.duplicate': 'Duplicate',
  'hosts.context_menu.copy': 'Copy',
  'hosts.context_menu.copy_ssh_cmd': 'SSH Command',
  'hosts.context_menu.copy_host_ip': 'Host / IP',
  'hosts.context_menu.copy_user_host': 'user@host',
  'hosts.context_menu.copied_snackbar': '{label} copied to clipboard',
  'hosts.context_menu.duplicated_snackbar': 'Duplicated "{label}"',
  'hosts.context_menu.moved_snackbar': 'Moved "{label}" to {folder}',
  'hosts.context_menu.remove': 'Remove',
  'hosts.form.title_new': 'New SSH Host',
  'hosts.form.title_edit': 'Edit Host',
  'hosts.form.label_field': 'Label / Alias',
  'hosts.form.label_hint': 'e.g. Production Web 01',
  'hosts.form.label_required': 'Label is required',
  'hosts.form.hostname_field': 'Hostname / IP',
  'hosts.form.hostname_hint': '192.168.1.1 or example.com',
  'hosts.form.hostname_required': 'Hostname is required',
  'hosts.form.port_field': 'Port',
  'hosts.form.port_invalid': 'Invalid',
  'hosts.form.username_field': 'Username',
  'hosts.form.username_hint': 'root, ubuntu, etc.',
  'hosts.form.username_required': 'Username is required',
  'hosts.form.auth_method': 'Auth Method',
  'hosts.form.password_field': 'SSH Password',
  'hosts.form.password_edit_hint': 'SSH Password (leave blank to keep current)',
  'hosts.form.password_hint': 'Enter server password',
  'hosts.form.key_field': 'SSH Key (from Keychain)',
  'hosts.form.key_none': 'None (Use system agent or prompt)',
  'hosts.form.environment_field': 'Environment',
  'hosts.form.environment_helper':
      'OS / Distribution is auto-detected upon SSH connection',
  'hosts.form.folder_field': 'Folder',
  'hosts.form.folder_root': 'No Folder (Root)',
  'hosts.form.tooltip_create_folder': 'Create New Folder',
  'hosts.form.dialog_folder_title': 'Create New Folder',
  'hosts.form.dialog_folder_name': 'Folder Name',
  'hosts.form.dialog_folder_hint': 'e.g. EU Datacenter',
  'hosts.form.dialog_folder_btn': 'Create',
  'hosts.form.tags_field': 'Tags (comma separated)',
  'hosts.form.tags_hint': 'web, db, k8s',
  'hosts.form.prod_guard_title': 'Production Command Guard',
  'hosts.form.prod_guard_subtitle':
      'Intercept destructive commands (rm -rf, reboot, etc.) and require confirmation',
  'hosts.form.btn_create': 'Create',
  'hosts.form.btn_save': 'Save Changes',

  // Keychain & SSH Keys
  'keychain.title': 'SSH Keychain & Certificates',
  'keychain.btn_import': 'Import ~/.ssh',
  'keychain.btn_generate': 'Generate Key',
  'keychain.tooltip_add_pem': 'Add Key Manually (PEM)',
  'keychain.empty_title': 'No SSH Keys in Vault',
  'keychain.empty_desc':
      'Generate a modern Ed25519 key or import existing keys from your local ~/.ssh folder',
  'keychain.btn_generate_pair': 'Generate Key Pair',
  'keychain.btn_import_ssh': 'Import from ~/.ssh',
  'keychain.card_passphrase_badge': 'PASSPHRASE',
  'keychain.card_fingerprint': 'Fingerprint: {fp}',
  'keychain.card_created': 'Created: {date}',
  'keychain.tooltip_copy_public': 'Copy Public Key',
  'keychain.tooltip_deploy_key': 'Deploy Key to Server (ssh-copy-id)',
  'keychain.tooltip_view_details': 'View Details',
  'keychain.tooltip_delete_key': 'Delete Key',
  'keychain.copied_public_key': 'Public key copied to clipboard!',
  'keychain.error_loading': 'Error loading keys: {error}',
  'keychain.details_title': 'Key Details',
  'keychain.details_type': 'Type: {type}',
  'keychain.details_public_key_label': 'Public Key:',
  'keychain.delete_dialog_title': 'Delete SSH Key?',
  'keychain.delete_dialog_desc':
      'Are you sure you want to delete "{label}"? Any servers relying exclusively on this key will need another authentication method.',
  'keychain.add_pem_title': 'Add SSH Key Manually (PEM)',
  'keychain.add_pem_label_field': 'Key Label *',
  'keychain.add_pem_label_hint': 'e.g. id_ed25519_custom',
  'keychain.add_pem_pem_field': 'Private Key PEM Content *',
  'keychain.add_pem_passphrase_field': 'Passphrase (if key is encrypted)',
  'keychain.add_pem_error_required':
      'Please fill in key label and PEM content.',
  'keychain.add_pem_btn_validate_save': 'Validate & Save',
  'keychain.generate_dialog_title': 'Generate SSH Key Pair',
  'keychain.generate_dialog_generated_title': 'Key Generated!',
  'keychain.generate_dialog_label_field': 'Key Label *',
  'keychain.generate_dialog_type_field': 'Key Algorithm',
  'keychain.generate_dialog_comment_field': 'Key Comment (Public)',
  'keychain.generate_dialog_passphrase_field': 'Key Passphrase (Optional)',
  'keychain.generate_dialog_passphrase_hint': 'Encrypt private key in vault',
  'keychain.generate_dialog_btn_generate': 'Generate & Save to Vault',
  'keychain.generate_dialog_success_desc':
      'Key pair successfully generated and saved to encrypted vault.',
  'keychain.generate_dialog_public_key_label':
      'Public Key (Ready for authorized_keys):',
  'keychain.generate_dialog_btn_copy_public': 'Copy Public Key',
  'keychain.generate_dialog_btn_deploy': 'Deploy to Server',
  'keychain.import_dialog_title': 'Import from ~/.ssh',
  'keychain.import_dialog_scanning': 'Scanning ~/.ssh directory...',
  'keychain.import_dialog_no_keys_title': 'No SSH Keys Found',
  'keychain.import_dialog_dir_label': 'Directory: {dir}',
  'keychain.import_dialog_found_keys': 'Found {count} keys in {dir}',
  'keychain.import_dialog_select_all': 'Select All',
  'keychain.import_dialog_deselect_all': 'Deselect All',
  'keychain.import_dialog_badge_encrypted': 'Encrypted',
  'keychain.import_dialog_passphrase_field':
      'Key Passphrase (required to decrypt)',
  'keychain.import_dialog_btn_import_selected': 'Import Selected',
  'keychain.import_dialog_btn_importing': 'Importing...',
  'keychain.import_dialog_success_msg': 'Successfully imported keys: {count}',
  'keychain.deploy_dialog_title': 'Deploy Key to Server (ssh-copy-id)',
  'keychain.deploy_dialog_deploying_label': 'Deploying: {label} ({type})',
  'keychain.deploy_dialog_tab_saved_host': 'Saved Host',
  'keychain.deploy_dialog_tab_manual_host': 'Manual Host',
  'keychain.deploy_dialog_target_host_label': 'Target Host',
  'keychain.deploy_dialog_host_ip_label': 'Host IP or Domain *',
  'keychain.deploy_dialog_port_label': 'Port',
  'keychain.deploy_dialog_username_label': 'Username *',
  'keychain.deploy_dialog_password_label':
      'Server Password (for 1-time key deploy) *',
  'keychain.deploy_dialog_password_hint': 'Enter password to authenticate',
  'keychain.deploy_dialog_bind_checkbox':
      'Bind this key to the host in Shellit for future logins',
  'keychain.deploy_dialog_btn_deploy': 'Deploy Key',
  'keychain.deploy_dialog_btn_deploying': 'Deploying...',
  'keychain.deploy_dialog_already_present':
      'Key is already installed in ~/.ssh/authorized_keys on {host}',
  'keychain.deploy_dialog_success_msg':
      'Public key successfully added to ~/.ssh/authorized_keys on {host}!',

  // Plugins & Extensions
  'plugins.title': 'Desktop Plugin Extensions (.shellit)',
  'plugins.btn_install': 'Install .shellit',
  'plugins.empty_title': 'No plugins installed yet',
  'plugins.empty_desc':
      'Install .shellit extensions or language packs to extend Shellit functionality',
  'plugins.target_label': 'Target: {target}',
  'plugins.locale_label': 'Locale: {locale}',
  'plugins.btn_uninstall': 'Uninstall',
  'plugins.uninstall_confirm_title': 'Uninstall {name}?',
  'plugins.uninstall_confirm_desc':
      'Are you sure you want to remove this plugin and all its files?',
  'plugins.error_loading': 'Error loading plugins: {error}',
  'plugins.by_author': 'v{version} by {author} • {id}',
  'plugins.tooltip_uninstall': 'Uninstall Plugin',
  'plugins.permissions_label': 'Permissions: ',
  'plugins.permissions_none': 'None',
  'plugins.uninstall_success': 'Uninstalled {name}',
  'plugins.install_dialog_title': 'Install Plugin Package',
  'plugins.install_dialog_desc':
      'Enter full file path to .shellit (or .zip) bundle archive:',
  'plugins.install_dialog_path_field': 'Plugin Archive File Path',
  'plugins.install_dialog_path_hint': 'C:\\path\\to\\plugin.shellit',
  'plugins.install_dialog_btn_install': 'Install',
  'plugins.install_dialog_success': 'Plugin "{name}" installed safely!',
  'plugins.install_dialog_failed': 'Failed: {error}',
  'plugins.mcp_short_name': 'MCP AI',
  'plugins.docker_short_name': 'Docker',
  'plugins.open_plugin': 'Open {name}',
  'plugins.close_plugin': 'Close {name}',
  'plugins.docker_connect_ssh_first':
      'Connect to an SSH host first to use Docker plugin',
  'plugins.target_host': 'Target: {host}',
  'plugins.no_active_session': 'No Active Session',
  'plugins.unsupported_platform':
      'Desktop plugins are currently supported on Windows (WebView2).',
  'plugins.launch_failed': 'Failed to launch plugin: {error}',

  // MCP Server & AI Gateway Plugin
  'mcp.logs.title': 'Live AI Activity Log',
  'mcp.logs.tooltip_popout': 'Open detached log monitor on second monitor',
  'mcp.logs.tooltip_save': 'Save logs to .log file',
  'mcp.logs.tooltip_copy': 'Copy all logs to clipboard',
  'mcp.logs.tooltip_clear': 'Clear activity logs',
  'mcp.logs.btn_save': 'Save Logs (.log)',
  'mcp.logs.btn_copy_all': 'Copy All',
  'mcp.logs.btn_clear': 'Clear',

  // Snippets
  'snippets.title': 'Command Snippets Library',
  'snippets.btn_new': 'New Snippet',
  'snippets.search_placeholder':
      'Search snippets by title, command, or tags...',
  'snippets.empty_title': 'No Snippets Saved Yet',
  'snippets.empty_match': 'No snippets match "{query}"',
  'snippets.empty_desc':
      'Save frequently used commands for instant 1-click execution.',
  'snippets.btn_add_first': 'Add First Snippet',
  'snippets.tooltip_run': 'Execute in active terminal ({tab})',
  'snippets.tooltip_copy': 'Copy to clipboard',
  'snippets.copied_snackbar': 'Copied "{title}" to clipboard',
  'snippets.menu_edit': 'Edit',
  'snippets.menu_delete': 'Delete',
  'snippets.executed_snackbar': 'Executed "{title}" in {tab}',
  'snippets.dialog_new_title': 'New Command Snippet',
  'snippets.dialog_edit_title': 'Edit Snippet',
  'snippets.title_field': 'Snippet Title (e.g. Restart Docker Swarm)',
  'snippets.command_field': 'Command / Script',
  'snippets.desc_field': 'Description (Optional)',
  'snippets.tags_field': 'Tags (comma separated, e.g. docker, prod, logs)',
  'snippets.btn_create': 'Create Snippet',
  'snippets.btn_save': 'Save Changes',

  // Tunnels & Port Forwarding
  'tunnels.title': 'Port Forwarding & Tunnels',
  'tunnels.btn_new': 'New Tunnel',
  'tunnels.empty_title': 'No active port forwarding rules',
  'tunnels.type_local': 'LOCAL (L)',
  'tunnels.type_remote': 'REMOTE (R)',
  'tunnels.dialog_title': 'Add Port Forwarding Rule',
  'tunnels.rule_label': 'Rule Label (e.g. Redis Dev Tunnel)',
  'tunnels.forward_type': 'Forward Type',
  'tunnels.forward_local_opt': 'Local Forward (-L)',
  'tunnels.forward_remote_opt': 'Remote Forward (-R)',
  'tunnels.local_port': 'Local Port',
  'tunnels.remote_port': 'Remote Port',
  'tunnels.remote_host': 'Remote Target Host',
  'tunnels.btn_add': 'Add Rule',

  // Logs & Audit
  'audit.title': 'Logs & Audit Center',
  'audit.tab_system_logs': 'System Logs',
  'audit.tab_session_recordings': 'Session Recordings',
  'audit.search_logs': 'Search message, tag or error...',
  'audit.all_tags': 'All Tags',
  'audit.tooltip_autoscroll_on': 'Auto-scroll ON',
  'audit.tooltip_autoscroll_off': 'Auto-scroll OFF',
  'audit.tooltip_pause_stream': 'Pause Stream',
  'audit.tooltip_resume_stream': 'Resume Stream',
  'audit.tooltip_copy_filtered': 'Copy Filtered Logs',
  'audit.copied_logs': 'Logs copied to clipboard',
  'audit.tooltip_clear_buffer': 'Clear In-Memory Buffer',
  'audit.events_count': '{filtered} / {total} events',
  'audit.empty_logs': 'No logs captured yet',
  'audit.empty_filter': 'No logs match current filter',
  'audit.detail_title': 'Log Event Details [{level}]',
  'audit.tooltip_copy_event': 'Copy event',
  'audit.detail_timestamp': 'Timestamp',
  'audit.detail_tag': 'Tag',
  'audit.detail_level': 'Level',
  'audit.detail_message': 'Message (Sanitized):',
  'audit.detail_error': 'Error:',
  'audit.detail_stack_trace': 'Stack Trace:',
  'audit.rec_empty_title': 'No recorded SSH sessions found',
  'audit.rec_empty_desc':
      'When terminal sessions run with recording enabled, their logs appear here.',
  'audit.rec_btn_refresh': 'Refresh',
  'audit.rec_search_placeholder': 'Search session recordings...',
  'audit.rec_delete_tooltip': 'Delete recording',
  'audit.rec_select_hint': 'Select a session to inspect text output',
  'audit.rec_clean_text': 'Clean Text',
  'audit.rec_raw_vt100': 'Raw VT100',
  'audit.rec_copy_preview_tooltip': 'Copy preview text',
  'audit.rec_copied': 'Session log copied to clipboard',
  'audit.rec_close_preview_tooltip': 'Close preview',
  'audit.rec_loading_content': 'Loading log content...',
  'audit.rec_delete_dialog_title': 'Delete Recording?',
  'audit.rec_delete_dialog_desc':
      'This will delete the asciinema .cast and text log files from disk permanently.',

  // Sync Settings Card
  'sync.card_title': 'Self-Hosted Synchronization (E2EE)',
  'sync.card_subtitle':
      'Sync across devices via your personal VPS with Zero-Knowledge encryption',
  'sync.server_url_label': 'Server URL (HTTP / HTTPS)',
  'sync.server_url_hint':
      'e.g. http://192.168.1.50:8080 or https://sync.my-vps.net',
  'sync.vault_id_label': 'Vault ID (Namespace)',
  'sync.vault_id_hint': 'e.g. personal-vault',
  'sync.passphrase_label': 'Sync Passphrase (E2EE Encryption Key)',
  'sync.passphrase_helper':
      'Derived on your device via Argon2id. The server NEVER sees this password.',
  'sync.token_label': 'Registration Token (Optional)',
  'sync.token_helper':
      'Required only when creating a new vault on a token-protected server',
  'sync.allow_insecure_title':
      'Allow Insecure / Self-Signed Certificates & Plain HTTP',
  'sync.allow_insecure_subtitle':
      'Enable for local LAN IP, WireGuard / Tailscale without SSL, or self-signed HTTPS',
  'sync.btn_save_settings': 'Save Settings',
  'sync.btn_test_connection': 'Test Connection',
  'sync.btn_sync_now': 'Sync Now',
  'sync.btn_syncing': 'Syncing...',
  'sync.saved_success': 'Sync settings saved successfully',
  'sync.test_testing': 'Testing connection...',
  'sync.test_success': 'Connection successful! (Server Online)',
  'sync.test_failed': 'Connection failed',
  'sync.last_synced': 'Last synced: {time}',
  'sync.err_url_required': 'Server URL is required',
  'sync.err_vault_id_required': 'Vault ID is required',
  'sync.err_passphrase_required':
      'Sync Passphrase is required for E2EE encryption',
  'sync.syncing': 'Synchronizing with server...',
  'sync.sync_success':
      'Synced successfully (Rev {rev}, Pulled {pulled}, Pushed {pushed})',
  'sync.sync_complete_msg': 'Sync complete: {pulled} pulled, {pushed} pushed',
  'sync.sync_failed': 'Sync failed: {error}',

  // Tabs & OmniBar
  'omni.command_palette_tooltip': 'Command Palette (Ctrl+K)',
  'omni.search_placeholder': 'Type a command, host, or action (Ctrl+K)...',
  'omni.no_results': 'No matching commands or hosts found',
  'omni.hint_navigate': '↑↓ Navigate',
  'omni.hint_select': '↵ Select',
  'omni.hint_close': 'Esc Close',
  'omni.action_switch_active': 'Switch Tab (Active)',
  'omni.action_switch_tab': 'Switch Tab ({target})',
  'omni.action_connect_host': 'Connect SSH ({target})',
  'omni.action_split_h_title': 'Split Horizontally',
  'omni.action_split_h_desc': 'Split active terminal pane horizontally',
  'omni.action_split_v_title': 'Split Vertically',
  'omni.action_split_v_desc': 'Split active terminal pane vertically',
  'omni.action_split_2x2_title': 'Split 2x2 Grid',
  'omni.action_split_2x2_desc': 'Split into 4 terminal panes',
  'omni.action_lock_vault_title': 'Lock Vault',
  'omni.action_lock_vault_desc': 'Secure database and wipe keys from memory',
  'omni.theme_title': 'Set Terminal Theme: {theme}',
  'omni.theme_desc': 'Switch active color scheme',
  'tabs.new_tab_tooltip': 'New Tab (Open Hosts Catalog)',
  'tabs.menu_duplicate': 'Duplicate Session',
  'tabs.menu_open_terminal': 'Open Terminal for Host',
  'tabs.menu_open_sftp': 'Open SFTP for this Host',
  'tabs.menu_reconnect': 'Reconnect Session',
  'tabs.menu_split_h': 'Split Horizontally',
  'tabs.menu_split_v': 'Split Vertically',
  'tabs.menu_split_2x2': 'Split 2x2 Grid',
  'tabs.menu_split_single': 'Collapse to Single Pane',
  'tabs.menu_rename': 'Rename Tab...',
  'tabs.menu_color_tag': 'Set Color Tag...',
  'tabs.menu_pin': 'Pin Tab',
  'tabs.menu_unpin': 'Unpin Tab',
  'tabs.menu_close': 'Close Tab',
  'tabs.menu_close_others': 'Close Other Tabs',
  'tabs.menu_close_right': 'Close Tabs to the Right',
  'tabs.menu_close_disconnected': 'Close Disconnected Sessions',
  'tabs.rename_dialog_title': 'Rename Tab',
  'tabs.rename_dialog_hint': 'Enter custom tab name (e.g. Docker Logs)',
  'tabs.rename_dialog_reset': 'Reset to Default',
  'tabs.color_dialog_title': 'Set Tab Color Tag',
  'tabs.overflow_search_placeholder': 'Search open tabs...',
  'tabs.overflow_no_matches': 'No matching tabs',
  'tabs.overflow_all_tabs': 'All Open Tabs ({count})',

  // Terminal & SFTP Tabs
  'terminal.shortcuts_btn': 'Keys',
  'terminal.shortcuts_dialog_title': 'Terminal Keyboard Shortcuts',
  'terminal.context_menu_copy': 'Copy',
  'terminal.context_menu_paste': 'Paste',
  'terminal.context_menu_select_all': 'Select All',
  'terminal.context_menu_clear': 'Clear Buffer',
  'terminal.context_menu_shortcuts': 'Shortcuts & Help',
  'terminal.shortcuts_tooltip': 'Keyboard Shortcuts (F1)',
  'terminal.sftp_tooltip': 'Open SFTP for this host',
  'terminal.rec_start_tooltip': 'Start Session Recording',
  'terminal.rec_stop_tooltip': 'Session Recording Active (Click to Stop)',

  // Prod Guard & Connecting View
  'prod_guard.dialog_title': 'PROD GUARD: Destructive Command',
  'prod_guard.warn_prefix': 'You are about to execute a dangerous command on ',
  'prod_guard.warn_suffix': ' (PRODUCTION):',
  'prod_guard.warn_footer':
      'This action may lead to data loss or service unavailability. Are you absolutely sure?',
  'prod_guard.btn_abort': 'Cancel (Abort)',
  'prod_guard.btn_execute': 'Execute Anyway',
  'connecting.status_default': 'Establishing SSH connection...',
  'connecting.header_title': 'Connecting Host',
  'connecting.step_decrypt': 'Decrypt credentials & keys',
  'connecting.step_tcp': 'Connect TCP socket',
  'connecting.step_handshake': 'SSH protocol handshake',
  'connecting.step_auth': 'User authentication',
  'connecting.step_shell': 'Allocate remote shell / subsystem',
  'connecting.btn_cancel': 'Cancel Connection',
  'connecting.vault_locked_title': 'Master Password Required',
  'connecting.vault_locked_desc':
      'Credentials for this host (password or key) are encrypted in the vault. Enter master password to connect.',
  'connecting.btn_unlock_vault': 'Unlock Vault',
  'connecting.btn_close_tab': 'Close Tab',
  'connecting.failed_title': 'Connection Failed',
  'connecting.btn_retry': 'Retry',

  // Splits & Broadcast
  'splits.single': 'Single Terminal',
  'splits.horizontal': 'Split Horizontal (Side by side)',
  'splits.vertical': 'Split Vertical (Top & bottom)',
  'splits.grid_2x2': '2x2 Matrix Split',
  'splits.broadcast_label': 'Broadcast Input',
  'splits.broadcast_alert': 'INPUT SENT TO ALL PANES',
  'splits.nav_hint': 'Alt + Arrows to navigate splits',
  'splits.picker_title': 'Connect Host to Split Pane {index}',
  'splits.picker_search': 'Search hosts by label, IP, username, or tag...',
  'splits.picker_no_hosts': 'No matching hosts found',
  'splits.picker_quick_title': 'Quick Connect: {target}',
  'splits.picker_quick_subtitle':
      'Connect to {user}@{host}:{port} as transient host',

  // SFTP Operations & Dialogs
  'sftp.menu_upload': 'Upload to Server',
  'sftp.menu_reveal': 'Show in File Explorer',
  'sftp.menu_copy_path': 'Copy Local Path',
  'sftp.menu_rename': 'Rename',
  'sftp.menu_delete': 'Delete',
  'sftp.menu_new_dir': 'New Directory',
  'sftp.menu_new_file': 'New File',
  'sftp.menu_refresh': 'Refresh',
  'sftp.menu_download': 'Download',
  'sftp.menu_chmod': 'Permissions (chmod)',
  'sftp.menu_copy_remote_path': 'Copy Remote Path',
  'sftp.empty_directory': 'Empty directory',
  'sftp.drop_files_hint': 'Drop files here or use buttons above',
  'sftp.queue_title': 'Transfers ({active} active, {total} total)',
  'sftp.queue_clear': 'Clear Completed',
  'sftp.dialog_chmod_title': 'Permissions: {file}',
  'sftp.dialog_chmod_read': 'Read (r)',
  'sftp.dialog_chmod_write': 'Write (w)',
  'sftp.dialog_chmod_exec': 'Exec (x)',
  'sftp.dialog_chmod_owner': 'Owner',
  'sftp.dialog_chmod_group': 'Group',
  'sftp.dialog_chmod_others': 'Others',
  'sftp.dialog_chmod_octal': 'Octal notation:',
  'sftp.dialog_rename_title': 'Rename',
  'sftp.dialog_rename_new_name': 'New name',
  'sftp.dialog_create_dir_title': 'New Directory',
  'sftp.dialog_create_file_title': 'New File',
  'sftp.dialog_create_dir_label': 'Directory name',
  'sftp.dialog_create_file_label': 'File name',
  'sftp.dialog_delete_title_dir': 'Delete Directory',
  'sftp.dialog_delete_title_file': 'Delete File',
  'sftp.dialog_delete_confirm': 'Are you sure you want to delete "{name}"?',
  'sftp.dialog_delete_warning':
      'This will recursively delete the directory and all of its contents. This action cannot be undone.',

  // SFTP Panes & Dialogs (Unified)
  'sftp.rename_title': 'Rename',
  'sftp.rename_label': 'New name',
  'sftp.rename_btn': 'Rename',
  'sftp.create_dir_title': 'New Directory',
  'sftp.create_file_title': 'New File',
  'sftp.create_dir_label': 'Directory name',
  'sftp.create_file_label': 'File name',
  'sftp.create_dir_hint': 'folder_name',
  'sftp.create_file_hint': 'filename.txt',
  'sftp.delete_dir_title': 'Delete Directory',
  'sftp.delete_file_title': 'Delete File',
  'sftp.delete_confirm_msg': 'Are you sure you want to delete "{name}"?',
  'sftp.delete_dir_warning':
      'This will recursively delete the directory and all of its contents. This action cannot be undone.',
  'sftp.transfers_summary': 'Transfers ({active} active, {total} total)',
  'sftp.upload_to_server': 'Upload to Server',
  'sftp.show_in_explorer': 'Show in File Explorer',
  'sftp.copy_local_path': 'Copy Local Path',
  'sftp.copy_remote_path': 'Copy Remote Path',
  'sftp.permissions_chmod': 'Permissions (chmod)',
  'sftp.rename': 'Rename',
  'sftp.copied_path': 'Copied: {path}',
  'sftp.new_directory': 'New Directory',
  'sftp.new_file': 'New File',
  'sftp.hide_hidden_files': 'Hide Hidden Files',
  'sftp.show_hidden_files': 'Show Hidden Files',
  'sftp.local_title': 'Local',
  'sftp.remote_title': 'Remote',
  'sftp.go_up': 'Go Up',
  'sftp.home_folder': 'Home Folder',
  'sftp.upload': 'Upload',
  'sftp.download': 'Download',
  'sftp.empty_folder': 'Empty folder',
  'sftp.no_items_hidden': 'No items (hidden files excluded)',

  // Settings & Themes & Logs extra
  'settings.theme_obsidian': 'Obsidian Dark',
  'settings.theme_dracula': 'Dracula',
  'settings.theme_nord': 'Nord',
  'settings.theme_oled': 'OLED True Black',
  'settings.theme_cyberpunk': 'Cyberpunk',
  'settings.logs.level_debug': 'Debug (Verbose)',
  'settings.logs.level_info': 'Info (Default)',
  'settings.logs.level_warn_error': 'Warning & Error',
  'settings.logs.level_error_only': 'Error Only',
  'settings.logs.rec_prod': 'PROD Only (Recommended)',
  'settings.logs.rec_all': 'All Sessions',
  'settings.logs.rec_manual': 'Manual (REC button only)',
  'settings.logs.files_deleted_msg': 'Disk log files deleted successfully',
  'settings.export_template.title': 'Export Translation Template',
  'settings.export_template.description':
      'Export complete master strings dictionary (JSON) to create custom language plugins or submit community translations:',
  'settings.export_template.path_label': 'Output File Path (Optional)',
  'settings.export_template.path_hint':
      'Leave empty for default Downloads folder',
  'settings.export_template.success_msg':
      'Template exported successfully to: {path}',
  'settings.export_template.error_msg': 'Export failed: {err}',
  'settings.export_template.btn_export': 'Export Template',

  // AI Assistant & Gemini Settings
  'settings.ai.section_title': 'AI Assistant & Gemini',
  'settings.ai.enable_title': 'Enable AI Snippet Assistant',
  'settings.ai.enable_subtitle':
      'Use Google Gemini to generate, explain, and optimize terminal commands',
  'settings.ai.api_key_label': 'Gemini API Key',
  'settings.ai.api_key_hint': 'AIzaSy...',
  'settings.ai.get_key_link': 'Get free API key at Google AI Studio ↗',
  'settings.ai.model_label': 'AI Model',
  'settings.ai.refresh_models_tooltip':
      'Refresh available models from Gemini API',
  'settings.ai.test_connection_btn': 'Test Connection',
  'settings.ai.test_success':
      'Successfully connected! {count} models available.',
  'settings.ai.test_failed': 'Connection failed: {error}',
  'settings.ai.recommended_badge': 'Recommended',
  'settings.ai.save_btn': 'Save AI Settings',
  'settings.ai.saved_msg': 'AI settings saved successfully',

  // Snippets AI Chat
  'snippets.tab_library': 'Library',
  'snippets.tab_ai_assistant': 'AI Assistant',
  'snippets.ai.welcome_title': 'AI Snippet Assistant',
  'snippets.ai.welcome_desc':
      'Describe any task or command you need in plain English or Russian, and Gemini will generate ready-to-run shell scripts.',
  'snippets.ai.need_key_title': 'Gemini API Key Required',
  'snippets.ai.need_key_desc':
      'Please configure your free Gemini API key in Settings to use the AI Snippet Assistant.',
  'snippets.ai.btn_open_settings': 'Open Settings',
  'snippets.ai.chat_placeholder':
      'Ask for a snippet (e.g. find files >100MB, docker cleanup, kill port 8080)...',
  'snippets.ai.btn_send': 'Send',
  'snippets.ai.btn_clear_chat': 'Clear Chat',
  'snippets.ai.active_model': 'Model: {model}',
  'snippets.ai.btn_save_snippet': 'Save to Snippets',
  'snippets.ai.btn_run_terminal': 'Run in Terminal',
  'snippets.ai.saved_success': 'Snippet "{title}" saved to library',
  'snippets.ai.executed_success': 'Command sent to terminal ({tab})',
  'snippets.ai.no_active_terminal':
      'No active terminal session to execute command',
  'snippets.ai.danger_badge': 'DESTRUCTIVE COMMAND',
  'snippets.ai.quick_docker': 'Docker clean stopped containers',
  'snippets.ai.quick_large_files': 'Find files >100MB',
  'snippets.ai.quick_ports': 'List listening TCP ports',
  'snippets.ai.quick_ram': 'Top 10 memory consuming processes',
  'snippets.ai.quick_logs': 'Compress logs older than 7 days',
  'snippets.ai.error_prefix': 'AI Error: {error}',
  'snippets.ai.thinking': 'Generating snippet...',

  // Hosts error
  'hosts.failed_to_connect': 'Failed to connect: {err}',

  // Unlock Vault Dialog
  'vault.status_locked': 'Locked',
  'vault.status_open': 'Open',
  'vault.unlock_title': 'Unlock Shellit Vault',
  'vault.unlock_desc':
      'Enter your master passphrase to unlock hosts, credentials, and private keys.',
  'vault.unlock_password_label': 'Master Password',
  'vault.unlock_btn': 'Unlock Vault',
  'vault.unlocked_success': 'Vault unlocked successfully.',
  'vault.unlock_failed': 'Invalid master password. Please try again.',

  // Local Terminal & Shells
  'local_terminal.btn.label': 'Terminal',
  'local_terminal.tooltip.open_default': 'Open Local Terminal ({shell})',
  'local_terminal.tooltip.select_shell': 'Select local shell',
  'local_terminal.menu.default_tag': 'Default',
  'local_terminal.menu.set_default': 'Set as default',
  'local_terminal.tab.title': 'Terminal ({shell})',
  'local_terminal.tab.badge': 'LOCAL',
  'local_terminal.status.process_exited': 'Process exited with code {code}',
  'local_terminal.error.launch_failed': 'Failed to launch local shell: {error}',
  'omni.action.open_local_terminal': 'Open Local Terminal ({shell})',

  // About Shellit Card
  'settings.about.section_title': 'About Shellit',
  'settings.about.version_tag': 'v{version}',
  'settings.about.status_preview': 'Preview',
  'settings.about.check_updates_btn': 'Check for updates',
  'settings.about.checking_updates': 'Checking for updates...',
  'settings.about.latest_version_installed':
      'You have the latest version of Shellit installed ({version}).',
  'settings.about.update_available_title': 'Update Available',
  'settings.about.update_available_msg':
      'A new version of Shellit is available: {version}',
  'settings.about.download_update_btn': 'Download Update',
  'settings.about.report_issue_title': 'Report an Issue',
  'settings.about.report_issue_subtitle': 'Open pre-filled report on GitHub',
  'settings.about.community_title': 'Community',
  'settings.about.community_subtitle': 'Telegram (Coming soon)',
  'settings.about.community_planned_msg':
      'Telegram community chat is in preparation and will launch with the public release.',
  'settings.about.github_title': 'GitHub',
  'settings.about.github_subtitle': 'Source code repository',
  'settings.about.changelog_title': "What's New",
  'settings.about.changelog_subtitle': 'View release highlights and changes',
  'settings.about.changelog_dialog_title': "What's New in Shellit",
  'settings.about.view_all_releases_btn': 'All Releases on GitHub',
  'settings.about.error_checking_updates':
      'Could not check for updates. Check your internet connection.',
};
